name: gitleaks
on:
  push:
jobs:
  scan:
    uses: knostic/.github/.github/workflows/gitleaks.yaml@dcc58a2ba99425861ace0857b8644eb2165f2aed
    with:
      event_name: ${{ github.event_name }}
      before_sha: ${{ github.event.before || '' }}
      forced: ${{ github.event.forced == true }}
    secrets: inherit
