name: gitleaks
on:
  push:
jobs:
  scan:
    uses: knostic/.github/.github/workflows/gitleaks.yaml@fix/gitleaks-scan-range
    with:
      event_name: ${{ github.event_name }}
      before_sha: ${{ github.event.before || '' }}
      forced: ${{ github.event.forced == true }}
    secrets: inherit
